// Generated by tsubabindgen (v0)
import type { i32 } from "@tsuba/core/types.js";

export const ANSWER: i32;
export declare class Color {
  private constructor();
  static readonly Red: Color;
  static readonly Green: Color;
}
export declare class Point {
  x: i32;
  y: i32;
  constructor(x: i32, y: i32);
  sum(): i32;
  static origin(): Point;
}
export function add(a: i32, b: i32): i32;
