// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:117:368
struct Counter {
  pub value: i32,
}

// tsuba-span: <SOURCE>:117:368
impl Counter {
  // tsuba-span: <SOURCE>:117:368
  pub fn new(seed: i32) -> Counter {
    return Counter { value: seed };
  }

  // tsuba-span: <SOURCE>:216:305
  pub fn inc(&mut self) {
    // tsuba-span: <SOURCE>:255:300
    self.value = (((self.value + ((1) as i32)))) as i32;
  }

  // tsuba-span: <SOURCE>:309:366
  pub fn get(&self) -> i32 {
    // tsuba-span: <SOURCE>:344:362
    return self.value;
  }
}

// tsuba-span: <SOURCE>:370:534
fn main() {
  // tsuba-span: <SOURCE>:407:452
  let mut counter: Counter = Counter::new((4) as i32);
  // tsuba-span: <SOURCE>:456:469
  counter.inc();
  // tsuba-span: <SOURCE>:473:486
  counter.inc();
  // tsuba-span: <SOURCE>:490:531
  println!("class-struct {}", counter.get());
}
