// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:161:197
#[repr(C)]
struct User {
  pub id: i32,
}

// tsuba-span: <SOURCE>:161:197
impl User {
  // tsuba-span: <SOURCE>:161:197
  pub fn new() -> User {
    return User { id: (0) as i32 };
  }
}

// tsuba-span: <SOURCE>:241:299
fn main() {
  // tsuba-span: <SOURCE>:274:296
  println!("annotate ok");
}
