// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:99:182
enum Shape {
  Circle { radius: i32 },
  Square { side: i32 },
}

// tsuba-span: <SOURCE>:184:322
fn area(s: Shape) -> i32 {
  // tsuba-span: <SOURCE>:217:320
  match s {
    Shape::Circle { radius: radius } => {
      // tsuba-span: <SOURCE>:260:276
      return radius;
    },
    Shape::Square { side: side } => {
      // tsuba-span: <SOURCE>:302:316
      return side;
    },
  }
}

// tsuba-span: <SOURCE>:324:443
fn main() {
  // tsuba-span: <SOURCE>:363:408
  let s: Shape = Shape::Square { side: (9) as i32 };
  // tsuba-span: <SOURCE>:412:440
  println!("union {}", area(s));
}
