// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:104:158
trait Scoreable {
  // tsuba-span: <SOURCE>:128:156
  fn score(&self) -> i32;
}

// tsuba-span: <SOURCE>:160:415
struct Pair {
  pub left: i32,
  pub right: i32,
}

// tsuba-span: <SOURCE>:160:415
impl Scoreable for Pair {
  // tsuba-span: <SOURCE>:336:413
  fn score(&self) -> i32 {
    // tsuba-span: <SOURCE>:370:409
    return (((self.left + self.right))) as i32;
  }
}

// tsuba-span: <SOURCE>:160:415
impl Pair {
  // tsuba-span: <SOURCE>:160:415
  pub fn new(left: i32, right: i32) -> Pair {
    return Pair { left: left, right: right };
  }

  // tsuba-span: <SOURCE>:336:413
  pub fn score(&self) -> i32 {
    // tsuba-span: <SOURCE>:370:409
    return (((self.left + self.right))) as i32;
  }
}

// tsuba-span: <SOURCE>:417:500
enum Shape {
  Circle { radius: i32 },
  Square { side: i32 },
}

// tsuba-span: <SOURCE>:502:640
fn area(s: Shape) -> i32 {
  // tsuba-span: <SOURCE>:535:638
  match s {
    Shape::Circle { radius: radius } => {
      // tsuba-span: <SOURCE>:578:594
      return radius;
    },
    Shape::Square { side: side } => {
      // tsuba-span: <SOURCE>:620:634
      return side;
    },
  }
}

// tsuba-span: <SOURCE>:642:715
fn scoreOne<T: Scoreable>(x: T) -> i32 {
  // tsuba-span: <SOURCE>:696:713
  return x.score();
}

// tsuba-span: <SOURCE>:717:917
fn main() {
  // tsuba-span: <SOURCE>:756:791
  let pair = Pair::new((3) as i32, (4) as i32);
  // tsuba-span: <SOURCE>:801:875
  let total = (((scoreOne(pair) + area(Shape::Square { side: (5) as i32 })))) as i32;
  // tsuba-span: <SOURCE>:879:914
  println!("object-context {}", total);
}
