// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:117:371
struct Counter {
  pub value: i32,
}

// tsuba-span: <SOURCE>:117:371
impl Counter {
  // tsuba-span: <SOURCE>:117:371
  pub fn new(value: i32) -> Counter {
    return Counter { value: value };
  }

  // tsuba-span: <SOURCE>:218:307
  pub fn inc(&mut self) {
    // tsuba-span: <SOURCE>:257:302
    self.value = (((self.value + ((1) as i32)))) as i32;
  }

  // tsuba-span: <SOURCE>:311:369
  pub fn read(&self) -> i32 {
    // tsuba-span: <SOURCE>:347:365
    return self.value;
  }
}

// tsuba-span: <SOURCE>:373:456
fn tick(counter: &mut Counter) {
  // tsuba-span: <SOURCE>:423:436
  counter.inc();
  // tsuba-span: <SOURCE>:440:453
  counter.inc();
}

// tsuba-span: <SOURCE>:458:600
fn main() {
  // tsuba-span: <SOURCE>:495:540
  let mut counter: Counter = Counter::new((0) as i32);
  // tsuba-span: <SOURCE>:544:557
  tick(&mut (counter));
  // tsuba-span: <SOURCE>:561:597
  println!("borrow {}", counter.read());
}
