// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:99:240
fn main() {
  // tsuba-span: <SOURCE>:138:150
  let x = (1) as i32;
  // tsuba-span: <SOURCE>:154:211
  {
    // tsuba-span: <SOURCE>:166:178
    let x = (2) as i32;
    // tsuba-span: <SOURCE>:184:206
    println!("inner {}", x);
  }
  // tsuba-span: <SOURCE>:214:237
  println!("shadow {}", x);
}
