// Generated by @tsuba/compiler (v0)

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:104:156
trait Readable {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:127:154
  fn read(&self) -> i32;
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:158:224
trait Named: Readable {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:195:222
  fn name(&self) -> i32;
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:226:286
trait Doubler {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:248:284
  fn twice(&self, x: i32) -> i32;
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:288:374
trait PickerLike<T: Named> {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:330:372
  fn pick(&self, value: &T) -> i32;
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:376:708
struct Adder {
  pub base: i32,
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:376:708
impl Named for Adder {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:556:633
  fn name(&self) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:590:629
    return (((self.base + ((1) as i32)))) as i32;
  }
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:376:708
impl Readable for Adder {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:497:552
  fn read(&self) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:531:548
    return self.base;
  }
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:376:708
impl Doubler for Adder {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:637:706
  fn twice(&self, x: i32) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:680:702
    return (((x + x))) as i32;
  }
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:376:708
impl Adder {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:376:708
  pub fn new(base: i32) -> Adder {
    return Adder { base: base };
  }

  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:497:552
  pub fn read(&self) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:531:548
    return self.base;
  }

  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:556:633
  pub fn name(&self) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:590:629
    return (((self.base + ((1) as i32)))) as i32;
  }

  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:637:706
  pub fn twice(&self, x: i32) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:680:702
    return (((x + x))) as i32;
  }
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:710:836
struct Picker;

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:710:836
impl PickerLike<Adder> for Picker {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:756:834
  fn pick(&self, value: &Adder) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:810:830
    return value.read();
  }
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:710:836
impl Picker {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:710:836
  pub fn new() -> Picker {
    return Picker;
  }

  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:756:834
  pub fn pick(&self, value: &Adder) -> i32 {
    // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:810:830
    return value.read();
  }
}

// tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:838:1026
fn main() {
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:877:900
  let a = Adder::new((9) as i32);
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:910:926
  let p = Picker::new();
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:936:993
  let total = ((((a.name() + p.pick(&(a))) + a.twice((2) as i32)))) as i32;
  // tsuba-span: /home/jester/repos/tsubalang/tsuba/test/fixtures/host-traits-generic/src/index.ts:997:1023
  println!("trait {}", total);
}
