// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:104:164
trait AdderLike {
  // tsuba-span: <SOURCE>:128:162
  fn add(&self, x: i32) -> i32;
}

// tsuba-span: <SOURCE>:166:359
struct Adder {
  pub base: i32,
}

// tsuba-span: <SOURCE>:166:359
impl AdderLike for Adder {
  // tsuba-span: <SOURCE>:282:357
  fn add(&self, x: i32) -> i32 {
    // tsuba-span: <SOURCE>:323:353
    return (((self.base + x))) as i32;
  }
}

// tsuba-span: <SOURCE>:166:359
impl Adder {
  // tsuba-span: <SOURCE>:166:359
  pub fn new(base: i32) -> Adder {
    return Adder { base: base };
  }

  // tsuba-span: <SOURCE>:282:357
  pub fn add(&self, x: i32) -> i32 {
    // tsuba-span: <SOURCE>:323:353
    return (((self.base + x))) as i32;
  }
}

// tsuba-span: <SOURCE>:361:466
fn main() {
  // tsuba-span: <SOURCE>:400:423
  let a = Adder::new((9) as i32);
  // tsuba-span: <SOURCE>:427:463
  println!("trait {}", a.add((4) as i32));
}
