// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:99:160
async fn compute() -> i32 {
  // tsuba-span: <SOURCE>:142:158
  return (7) as i32;
}

// tsuba-span: <SOURCE>:162:272
#[tokio::main]
async fn main() {
  // tsuba-span: <SOURCE>:216:239
  let value = (compute()).await;
  // tsuba-span: <SOURCE>:243:269
  println!("tokio {}", value);
}
