// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:99:161
fn add(a: i32, b: i32) -> i32 {
  // tsuba-span: <SOURCE>:137:159
  return (((a + b))) as i32;
}

// tsuba-span: <SOURCE>:163:263
fn main() {
  // tsuba-span: <SOURCE>:202:229
  let x = add((1) as i32, (2) as i32);
  // tsuba-span: <SOURCE>:233:260
  println!("host-basic {}", x);
}
