// Generated by @tsuba/compiler (v0)

// tsuba-span: <SOURCE>:99:161
fn add(a: i32, b: i32) -> i32 {
  // tsuba-span: <SOURCE>:137:159
  return (((a + b))) as i32;
}

// tsuba-span: <SOURCE>:163:268
fn main() {
  // tsuba-span: <SOURCE>:202:229
  let x = add((5) as i32, (6) as i32);
  // tsuba-span: <SOURCE>:233:265
  println!("workspace-basic {}", x);
}
